services:
  jenkins:
    build: . # builds from jenkins/Dockerfile
    user: root # simplest for socket access while learning
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
